name: 'Test Pull Request'
on: [pull_request]

permissions:
  contents: read

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: downcase Repo
        run: |
            echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false